name: Use External GoSec Action

on:
  push:
    branches: 
      - master 
  pull_request:
    branches: 
      - master 

jobs:
  use-external-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ggulsum/actions_/.github/workflows/gosec.yml@master

