name: Use External GoSec Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  use-external-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout_repo
        uses: actions/checkout@v2

      - name: Use External GoSec Action
        uses: ggulsum/actions_/.github/workflows/gosec.yml@master



