name: Use External GoSec Action

on:
  push:
    branches: 
      - master 
  pull_request:
    branches: 
      - master 

jobs:   
  use-external-action:
    uses: ggulsum/actions/.github/workflows/gosec.yml@master

