name: Use External GoSec Action

on:
  push:
    branches: 
      - master 
  pull_request:
    branches: 
      - master 

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World"
      
  use-external-action:
    uses: ggulsum/actions_/.github/workflows/gosec.yml@master
    



