name: Go Build and Gosec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  use-external-action:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Use shared GoSec action
      uses: ggulsum/actions_/.github/workflows/gosec.yml@master
