name: Call Reusable Go Build and Gosec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable Go Build and Gosec workflow
        uses: ggulsum/actions_/.github/workflows/gosec.yml
        with:
          go_version: '1.22'
          repository: 'ggulsum/api'
