name: Call Reusable Go Build and Gosec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-reusable-workflow:
    uses: ggulsum/actions_/.github/workflows/gosec.yml@master
    with:
      go_version: '1.22'
      repository: 'ggulsum/api'
